# Example: a throwaway NixOS VM that exercises the Dash0 Home Manager module.
#
# It boots a minimal NixOS guest with `programs.dash0` configured, so you can
# see profiles.json generated by the module's activation and read back by the
# CLI — without touching your host. See ./README.md for usage.
#
# By default this pulls the CLI from the published repository. To test a branch
# or a local checkout, override the input, e.g.:
#   nixos-rebuild build-vm --flake .#dash0vm \
#     --override-input dash0-cli github:dash0hq/dash0-cli/<branch>
#   nixos-rebuild build-vm --flake .#dash0vm \
#     --override-input dash0-cli path:/path/to/dash0-cli
{
  description = "Throwaway NixOS VM exercising the Dash0 Home Manager module";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    dash0-cli.url = "github:dash0hq/dash0-cli";
  };

  outputs =
    {
      nixpkgs,
      home-manager,
      dash0-cli,
      ...
    }:
    {
      nixosConfigurations.dash0vm = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          home-manager.nixosModules.home-manager
          (
            { ... }:
            {
              system.stateVersion = "24.11";

              # Auto-login on the VM console so you land in a shell that can run
              # the CLI immediately.
              services.getty.autologinUser = "alice";
              users.users.alice = {
                isNormalUser = true;
                initialPassword = "test";
              };

              # A demo static token. This is intentionally a world-readable file
              # for the example — do NOT do this for real secrets; use a
              # sops-nix/agenix secret path for authTokenFile instead.
              environment.etc."dash0/demo-token".text = "auth_demo_not_a_real_token";

              home-manager.users.alice = {
                imports = [ dash0-cli.homeManagerModules.default ];
                home.stateVersion = "24.11";

                programs.dash0 = {
                  enable = true;
                  activeProfile = "prod";

                  # Two OAuth profiles (seeded; run `dash0 login` to fill them)
                  # and one static profile reading its token from a file.
                  profiles.prod = {
                    apiUrl = "https://api.eu-west-1.aws.dash0.com";
                    otlpUrl = "https://ingress.eu-west-1.aws.dash0.com";
                    dataset = "default";
                    auth = "oauth";
                  };
                  profiles.staging = {
                    apiUrl = "https://api.us-west-2.aws.dash0.com";
                    auth = "oauth";
                  };
                  profiles.ci = {
                    apiUrl = "https://api.us-west-2.aws.dash0.com";
                    auth = "static";
                    authTokenFile = "/etc/dash0/demo-token";
                  };
                };
              };
            }
          )
        ];
      };
    };
}
