project_name: dash0

before:
  hooks:
    - go mod download

builds:
  - id: dash0
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
      - s390x
    dir: ./
    main: ./cmd/dash0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}}

checksum:
  name_template: "checksums.txt"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: "false"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
      - "ghcr.io/dash0hq/cli:{{ .Tag }}-amd64"
      - "ghcr.io/dash0hq/cli:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "ghcr.io/dash0hq/cli:{{ .Tag }}-arm64"
      - "ghcr.io/dash0hq/cli:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/dash0hq/cli:{{ .Tag }}"
    image_templates:
      - "ghcr.io/dash0hq/cli:{{ .Tag }}-amd64"
      - "ghcr.io/dash0hq/cli:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/dash0hq/cli:latest"
    image_templates:
      - "ghcr.io/dash0hq/cli:latest-amd64"
      - "ghcr.io/dash0hq/cli:latest-arm64"

brews:
  - name: dash0
    tap:
      owner: dash0hq
      name: dash0-cli
    commit_author:
      name: bripkens
      email: ben.blackmore@dash0.com
    folder: Formula
    homepage: https://github.com/dash0hq/dash0-cli
    description: CLI to interact with Dash0
