// Package filtering provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package filtering

import (
	"encoding/json"

	externalRef0 "github.com/dash0hq/dash0-cli/internal/api/types/otlpcommon"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AttributeFilterOperator.
const (
	AttributeFilterOperatorContains         AttributeFilterOperator = "contains"
	AttributeFilterOperatorDoesNotContain   AttributeFilterOperator = "does_not_contain"
	AttributeFilterOperatorDoesNotEndWith   AttributeFilterOperator = "does_not_end_with"
	AttributeFilterOperatorDoesNotMatch     AttributeFilterOperator = "does_not_match"
	AttributeFilterOperatorDoesNotStartWith AttributeFilterOperator = "does_not_start_with"
	AttributeFilterOperatorEndsWith         AttributeFilterOperator = "ends_with"
	AttributeFilterOperatorGt               AttributeFilterOperator = "gt"
	AttributeFilterOperatorGte              AttributeFilterOperator = "gte"
	AttributeFilterOperatorIs               AttributeFilterOperator = "is"
	AttributeFilterOperatorIsAny            AttributeFilterOperator = "is_any"
	AttributeFilterOperatorIsNot            AttributeFilterOperator = "is_not"
	AttributeFilterOperatorIsNotOneOf       AttributeFilterOperator = "is_not_one_of"
	AttributeFilterOperatorIsNotSet         AttributeFilterOperator = "is_not_set"
	AttributeFilterOperatorIsOneOf          AttributeFilterOperator = "is_one_of"
	AttributeFilterOperatorIsSet            AttributeFilterOperator = "is_set"
	AttributeFilterOperatorLt               AttributeFilterOperator = "lt"
	AttributeFilterOperatorLte              AttributeFilterOperator = "lte"
	AttributeFilterOperatorMatches          AttributeFilterOperator = "matches"
	AttributeFilterOperatorStartsWith       AttributeFilterOperator = "starts_with"
)

// AttributeFilter defines model for AttributeFilter.
type AttributeFilter struct {
	// Key The attribute key to be filtered.
	Key AttributeFilterKey `json:"key"`

	// Operator The match operation. is = equals (attribute exists and has a matching value), is_not = not equals (attribute exists and has a different value), is_set = is set (attribute exists), is_not_set = is not set (attributes does not exist), is_one_of = is any of (attribute exists and has a value that is in the specified values), is_not_one_of = is not any of (attribute exists and has a value that is not in the specified values), gt = greater than, lt = less than, gte = greater than or equal, lte = less than or equal, matches = match regex expression (attribute exists and matches the regular expression), does_not_match = does not match regex expression (attribute exists and does not match the regular expression), contains = contains (attribute exists and contains the specified value), does_not_contain = does not contain (attribute exists and does not contain the specified value), starts_with = starts with (attribute exists and starts with the specified value), does_not_start_with = does not start with (attribute exists and does not start with the specified value), ends_with = ends with (attribute exists and ends with the specified value), does_not_end_with = does not end with (attribute exists and does not end with the specified value). is_any = Matches any value, ignoring whether the key exists or not.
	Operator AttributeFilterOperator `json:"operator"`
	Value    *AttributeFilter_Value  `json:"value,omitempty"`

	// Values List of values to match against. This parameter is mandatory for the is_one_of and is_not_one_of operators.
	Values *[]AttributeFilter_Values_Item `json:"values,omitempty"`
}

// AttributeFilter_Value defines model for AttributeFilter.Value.
type AttributeFilter_Value struct {
	union json.RawMessage
}

// AttributeFilter_Values_Item defines model for AttributeFilter.values.Item.
type AttributeFilter_Values_Item struct {
	union json.RawMessage
}

// AttributeFilterAnyValue AnyValue is used to represent any type of attribute value. AnyValue may contain a primitive value such as a string or integer or it may contain an arbitrary nested object containing arrays, key-value lists and primitives.
type AttributeFilterAnyValue = externalRef0.AnyValue

// AttributeFilterKey The attribute key to be filtered.
type AttributeFilterKey = string

// AttributeFilterOperator The match operation. is = equals (attribute exists and has a matching value), is_not = not equals (attribute exists and has a different value), is_set = is set (attribute exists), is_not_set = is not set (attributes does not exist), is_one_of = is any of (attribute exists and has a value that is in the specified values), is_not_one_of = is not any of (attribute exists and has a value that is not in the specified values), gt = greater than, lt = less than, gte = greater than or equal, lte = less than or equal, matches = match regex expression (attribute exists and matches the regular expression), does_not_match = does not match regex expression (attribute exists and does not match the regular expression), contains = contains (attribute exists and contains the specified value), does_not_contain = does not contain (attribute exists and does not contain the specified value), starts_with = starts with (attribute exists and starts with the specified value), does_not_start_with = does not start with (attribute exists and does not start with the specified value), ends_with = ends with (attribute exists and ends with the specified value), does_not_end_with = does not end with (attribute exists and does not end with the specified value). is_any = Matches any value, ignoring whether the key exists or not.
type AttributeFilterOperator string

// AttributeFilterStringValue AttributeFilterStringValue may contain a primitive value such as a regex pattern or string.
type AttributeFilterStringValue = string

// FilterCriteria defines model for FilterCriteria.
type FilterCriteria = []AttributeFilter

// AsAttributeFilterStringValue returns the union data inside the AttributeFilter_Value as a AttributeFilterStringValue
func (t AttributeFilter_Value) AsAttributeFilterStringValue() (AttributeFilterStringValue, error) {
	var body AttributeFilterStringValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAttributeFilterStringValue overwrites any union data inside the AttributeFilter_Value as the provided AttributeFilterStringValue
func (t *AttributeFilter_Value) FromAttributeFilterStringValue(v AttributeFilterStringValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAttributeFilterStringValue performs a merge with any union data inside the AttributeFilter_Value, using the provided AttributeFilterStringValue
func (t *AttributeFilter_Value) MergeAttributeFilterStringValue(v AttributeFilterStringValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAttributeFilterAnyValue returns the union data inside the AttributeFilter_Value as a AttributeFilterAnyValue
func (t AttributeFilter_Value) AsAttributeFilterAnyValue() (AttributeFilterAnyValue, error) {
	var body AttributeFilterAnyValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAttributeFilterAnyValue overwrites any union data inside the AttributeFilter_Value as the provided AttributeFilterAnyValue
func (t *AttributeFilter_Value) FromAttributeFilterAnyValue(v AttributeFilterAnyValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAttributeFilterAnyValue performs a merge with any union data inside the AttributeFilter_Value, using the provided AttributeFilterAnyValue
func (t *AttributeFilter_Value) MergeAttributeFilterAnyValue(v AttributeFilterAnyValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AttributeFilter_Value) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AttributeFilter_Value) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAttributeFilterStringValue returns the union data inside the AttributeFilter_Values_Item as a AttributeFilterStringValue
func (t AttributeFilter_Values_Item) AsAttributeFilterStringValue() (AttributeFilterStringValue, error) {
	var body AttributeFilterStringValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAttributeFilterStringValue overwrites any union data inside the AttributeFilter_Values_Item as the provided AttributeFilterStringValue
func (t *AttributeFilter_Values_Item) FromAttributeFilterStringValue(v AttributeFilterStringValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAttributeFilterStringValue performs a merge with any union data inside the AttributeFilter_Values_Item, using the provided AttributeFilterStringValue
func (t *AttributeFilter_Values_Item) MergeAttributeFilterStringValue(v AttributeFilterStringValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAttributeFilterAnyValue returns the union data inside the AttributeFilter_Values_Item as a AttributeFilterAnyValue
func (t AttributeFilter_Values_Item) AsAttributeFilterAnyValue() (AttributeFilterAnyValue, error) {
	var body AttributeFilterAnyValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAttributeFilterAnyValue overwrites any union data inside the AttributeFilter_Values_Item as the provided AttributeFilterAnyValue
func (t *AttributeFilter_Values_Item) FromAttributeFilterAnyValue(v AttributeFilterAnyValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAttributeFilterAnyValue performs a merge with any union data inside the AttributeFilter_Values_Item, using the provided AttributeFilterAnyValue
func (t *AttributeFilter_Values_Item) MergeAttributeFilterAnyValue(v AttributeFilterAnyValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AttributeFilter_Values_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AttributeFilter_Values_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
