// Package time provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package time

import (
	"time"
)

// Duration defines model for Duration.
type Duration = string

// DurationOrVariable A duration or a variable that can be resolved to a duration.
// The variable can be one of:
//   - `$__interval`
//   - `$__rate_interval`
//   - `$__range`
type DurationOrVariable = string

// FixedTime defines model for FixedTime.
type FixedTime = time.Time

// FixedTimeUnix The time corresponding to the given unix time in seconds and nanoseconds (as decimal places) since January 1, 1970 UTC.
type FixedTimeUnix = string

// MinStepSize defines model for MinStepSize.
type MinStepSize = Duration

// Range A duration or a variable that can be resolved to a duration.
// The variable can be one of:
//   - `$__interval`
//   - `$__rate_interval`
//   - `$__range`
type Range = DurationOrVariable

// RelativeTime defines model for RelativeTime.
type RelativeTime = string

// RelativeTimeShift A relative time shift from the current time.
type RelativeTimeShift = string

// TimeRange defines model for TimeRange.
type TimeRange struct {
	From FixedTime `json:"from"`
	To   FixedTime `json:"to"`
}

// TimeReference defines model for TimeReference.
type TimeReference = any

// TimeReferenceRange A range of time between two time references.
type TimeReferenceRange struct {
	From TimeReference `json:"from"`
	To   TimeReference `json:"to"`
}

// TimeShift Used to implement comparison use cases without API clients having to resolve time references ranges.
//
// Can be set to a fixed point in time (through usage of `TimeReference`). In that case,
//   - `newTo=timeShift`
//   - `newFrom=newTo-(to-from)`.
type TimeShift = any
