// Package pagination provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package pagination

// Cursor The cursor to another set of results. The value of this field is opaque to the
// client and may be used as a parameter to the next request to get the another set of results.
// Cursors do not implement any ordering.
type Cursor = string

// CursorPagination Cursor pagination is a technique for paging through a result set using a cursor. It is
// similar to offset pagination except that the cursor is an opaque value that encodes the
// position within the result set. This allows for fetching the next page of results from
// the current position without having to skip over a potentially large number of rows.
//
// It is also more resilient against late-arriving data which otherwise would cause issues
// with offset pagination. For example, if a row is inserted between two pages of results
// then the second page would contain a duplicate row and the third page would be missing.
type CursorPagination struct {
	// Cursor The cursor to another set of results. The value of this field is opaque to the
	// client and may be used as a parameter to the next request to get the another set of results.
	// Cursors do not implement any ordering.
	Cursor *Cursor `json:"cursor,omitempty"`

	// Limit The maximum number of results to return. If not set, there is a default limit to the number of results returned.
	Limit *int64 `json:"limit,omitempty"`
}

// NextCursors defines model for NextCursors.
type NextCursors struct {
	// After The cursor to another set of results. The value of this field is opaque to the
	// client and may be used as a parameter to the next request to get the another set of results.
	// Cursors do not implement any ordering.
	After *Cursor `json:"after,omitempty"`

	// Before The cursor to another set of results. The value of this field is opaque to the
	// client and may be used as a parameter to the next request to get the another set of results.
	// Cursors do not implement any ordering.
	Before *Cursor `json:"before,omitempty"`
}
