// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package common

// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
type Dataset = string

// Error defines model for Error.
type Error struct {
	Code    int     `json:"code"`
	Message string  `json:"message"`
	TraceId *string `json:"traceId,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// Limit The maximum number of results to return. If not set, there is a default limit to the number of results returned.
type Limit = int64
