// Package alerting provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package alerting

import (
    externalRef0 "github.com/dash0hq/dash0-cli/internal/api/types/apiresources"
	externalRef1 "github.com/dash0hq/dash0-cli/internal/api/types/common"
    externalRef2 "github.com/dash0hq/dash0-cli/internal/api/types/d0time"
	externalRef3 "github.com/dash0hq/dash0-cli/internal/api/types/filtering"
	externalRef6 "github.com/dash0hq/dash0-cli/internal/api/types/ordering"
	externalRef7 "github.com/dash0hq/dash0-cli/internal/api/types/otlpcommon"
	externalRef8 "github.com/dash0hq/dash0-cli/internal/api/types/pagination"
    "github.com/google/uuid"
)

// AffectedResourceSummary defines model for AffectedResourceSummary.
type AffectedResourceSummary struct {
	// Clouds Key-Value pairs with information on cloud environments in which the resources are running.
	Clouds *[]externalRef0.ResourceAttributesBreakdown `json:"clouds,omitempty"`

	// Platforms Key-Value pairs with information on platforms (K8s, ECS...) in which the resources are running.
	Platforms *[]externalRef0.ResourceAttributesBreakdown `json:"platforms,omitempty"`

	// Runtimes Key-Value pairs with information on runtimes (Go, Java, Node.js...) in which the resources are running.
	Runtimes *[]externalRef0.ResourceAttributesBreakdown `json:"runtimes,omitempty"`

	// Services Key-Value pairs with information on services in which the resources are running.
	Services *[]externalRef0.ResourceAttributesBreakdown `json:"services,omitempty"`
}

// CheckRuleSummary defines model for CheckRuleSummary.
type CheckRuleSummary struct {
	DescriptionTemplate string             `json:"descriptionTemplate"`
	Id                  uuid.UUID `json:"id"`
	Name                string             `json:"name"`
	SummaryTemplate     string             `json:"summaryTemplate"`
	Version             int64              `json:"version"`
}

// GetIssuesRequest defines model for GetIssuesRequest.
type GetIssuesRequest struct {
	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset *externalRef1.Dataset        `json:"dataset,omitempty"`
	Filter  *externalRef3.FilterCriteria `json:"filter,omitempty"`

	// Ordering Any attribute keys to order by.
	Ordering *externalRef6.OrderingCriteria `json:"ordering,omitempty"`

	// Pagination Cursor pagination is a technique for paging through a result set using a cursor. It is
	// similar to offset pagination except that the cursor is an opaque value that encodes the
	// position within the result set. This allows for fetching the next page of results from
	// the current position without having to skip over a potentially large number of rows.
	//
	// It is also more resilient against late-arriving data which otherwise would cause issues
	// with offset pagination. For example, if a row is inserted between two pages of results
	// then the second page would contain a duplicate row and the third page would be missing.
	Pagination *externalRef8.CursorPagination `json:"pagination,omitempty"`

	// TimeRange A range of time between two time references.
	TimeRange externalRef2.TimeReferenceRange `json:"timeRange"`
}

// GetIssuesResponse defines model for GetIssuesResponse.
type GetIssuesResponse struct {
	Cursors       *externalRef8.NextCursors `json:"cursors,omitempty"`
	ExecutionTime externalRef2.FixedTime    `json:"executionTime"`
	Issues        []IssueListItem           `json:"issues"`
	TimeRange     externalRef2.TimeRange    `json:"timeRange"`
}

// IssueListItem defines model for IssueListItem.
type IssueListItem struct {
	// AffectedResourceSummaries A list of summaries for the affected resources. The summaries are used to provide a high-level overview
	// of the affected resources about the issue, e.g., X affected pods or Y affected services.
	AffectedResourceSummaries []AffectedResourceSummary `json:"affectedResourceSummaries"`
	Annotations               []externalRef7.KeyValue   `json:"annotations"`
	CheckRule                 CheckRuleSummary          `json:"checkRule"`
	Description               string                    `json:"description"`
	EarliestEvaluatedTime     *externalRef2.FixedTime   `json:"earliestEvaluatedTime,omitempty"`
	End                       *externalRef2.FixedTime   `json:"end,omitempty"`

	// Id The unique identifier of the issue. This field is generated by Dash0 and is globally unique.
	Id uuid.UUID `json:"id"`

	// IssueIdentifier An editable, templatable issue identifier that specifies how failing checks are grouped in terms
	// of UI and notifications. This is optional (and currently unsupported) because Dash0 has default
	// rules specifying how to group based on the returned label sets.
	IssueIdentifier string                  `json:"issueIdentifier"`
	Labels          []externalRef7.KeyValue `json:"labels"`
	Start           externalRef2.FixedTime  `json:"start"`
	Summary         string                  `json:"summary"`
}
