// Package otlpresourceextensions provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package otlpresourceextensions

// Defines values for ResourceOrchestration.
const (
	ResourceOrchestrationKubernetes ResourceOrchestration = "kubernetes"
)

// ResourceCloud Resource cloud identified based on the `cloud.provider` resource attribute. Some sample values:
// - alibaba_cloud
// - aws
// - azure
// - gcp
// - heroku
// - ibm_cloud
// - tencent_cloud
type ResourceCloud = string

// ResourceClouds defines model for ResourceClouds.
type ResourceClouds = []ResourceCloud

// ResourceDeploymentEnvironment The value of the `deployment.environment.name` (or `deployment.environment` pre v1.27 semconvs)
type ResourceDeploymentEnvironment = string

// ResourceDeploymentEnvironments defines model for ResourceDeploymentEnvironments.
type ResourceDeploymentEnvironments = []ResourceDeploymentEnvironment

// ResourceLanguage Resource language identified based on the `telemetry.sdk.language` resource attribute. Some sample values:
// - cpp
// - dotnet
// - erlang
// - go
// - java
// - nodejs
// - php
// - python
// - ruby
// - rust
// - swift
// - webjs
type ResourceLanguage = string

// ResourceLanguages defines model for ResourceLanguages.
type ResourceLanguages = []ResourceLanguage

// ResourceOrchestration Resource orchestration identified based on orchestration related resource attributes, e.g., existence
// of `k8s.*` resource attribute.
type ResourceOrchestration string

// ResourceOrchestrations defines model for ResourceOrchestrations.
type ResourceOrchestrations = []ResourceOrchestration
