// Package otlpresource provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package otlpresource

import (
	externalRef0 "github.com/dash0hq/dash0-cli/internal/api/types/otlpcommon"
	externalRef1 "github.com/dash0hq/dash0-cli/internal/api/types/otlpresourceextensions"
)

// Resource defines model for Resource.
type Resource struct {
	Attributes             []externalRef0.KeyValue                      `json:"attributes"`
	Clouds                 *externalRef1.ResourceClouds                 `json:"clouds,omitempty"`
	DeploymentEnvironments *externalRef1.ResourceDeploymentEnvironments `json:"deploymentEnvironments,omitempty"`
	DroppedAttributesCount *int64                                       `json:"droppedAttributesCount,omitempty"`

	// FirstSeenUnixNano The property is only included when `includeOTLPSchemaExtensions` is `true`.
	FirstSeenUnixNano *string                         `json:"firstSeenUnixNano,omitempty"`
	Languages         *externalRef1.ResourceLanguages `json:"languages,omitempty"`

	// LastSeenUnixNano The property is only included when `includeOTLPSchemaExtensions` is `true`.
	LastSeenUnixNano *string `json:"lastSeenUnixNano,omitempty"`

	// OperationTypes The property is only included when `includeOTLPSchemaExtensions` is `true`.
	OperationTypes *[]string                            `json:"operationTypes,omitempty"`
	Orchestrations *externalRef1.ResourceOrchestrations `json:"orchestrations,omitempty"`
}
