// Package apicomparisons provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apicomparisons

import (
	externalRef0 "github.com/dash0hq/dash0-cli/internal/api/types/common"
	externalRef1 "github.com/dash0hq/dash0-cli/internal/api/types/d0time"
	externalRef2 "github.com/dash0hq/dash0-cli/internal/api/types/filtering"
	externalRef3 "github.com/dash0hq/dash0-cli/internal/api/types/otlpcommon"
)

// AttributeComparisonRequest defines model for AttributeComparisonRequest.
type AttributeComparisonRequest struct {
	BaselineSelection   Selection  `json:"baselineSelection"`
	ComparisonSelection *Selection `json:"comparisonSelection,omitempty"`

	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset *externalRef0.Dataset        `json:"dataset,omitempty"`
	Filter  *externalRef2.FilterCriteria `json:"filter,omitempty"`

	// RetainCommonElements Determines whether elements that are common to both the baseline and the comparison selection are excluded
	// from the baseline or retained in both selections when an intersection occurs.
	RetainCommonElements *bool `json:"retainCommonElements,omitempty"`
}

// AttributeComparisonResponse defines model for AttributeComparisonResponse.
type AttributeComparisonResponse struct {
	Attributes *[]AttributeWithValueCounts `json:"attributes,omitempty"`
	Done       bool                        `json:"done"`
	Error      *externalRef0.Error         `json:"error,omitempty"`
	Key        string                      `json:"key"`
	Progress   *Progress                   `json:"progress,omitempty"`
}

// AttributeWithValueCounts defines model for AttributeWithValueCounts.
type AttributeWithValueCounts struct {
	Key    string            `json:"key"`
	Values []ValueWithCounts `json:"values"`
}

// Progress defines model for Progress.
type Progress struct {
	BytesRead       uint64 `json:"bytesRead"`
	RowsRead        uint64 `json:"rowsRead"`
	TotalRowsToRead uint64 `json:"totalRowsToRead"`
}

// Selection defines model for Selection.
type Selection struct {
	Filter *externalRef2.FilterCriteria `json:"filter,omitempty"`

	// TimeRange A range of time between two time references.
	TimeRange externalRef1.TimeReferenceRange `json:"timeRange"`
}

// ValueWithCounts defines model for ValueWithCounts.
type ValueWithCounts struct {
	BaselineCount  int  `json:"baselineCount"`
	SelectionCount *int `json:"selectionCount,omitempty"`

	// Value AnyValue is used to represent any type of attribute value. AnyValue may contain a primitive value such as a string or integer or it may contain an arbitrary nested object containing arrays, key-value lists and primitives.
	Value externalRef3.AnyValue `json:"value"`
}
