// Package filtering provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package filtering

import (

    externalRef3 "github.com/dash0hq/dash0-cli/internal/api/types/apiresources"
    externalRef5 "github.com/dash0hq/dash0-cli/internal/api/types/common"
    externalRef6 "github.com/dash0hq/dash0-cli/internal/api/types/d0time"
    externalRef8 "github.com/dash0hq/dash0-cli/internal/api/types/filtering"
    externalRef9 "github.com/dash0hq/dash0-cli/internal/api/types/grouping"
    externalRef10 "github.com/dash0hq/dash0-cli/internal/api/types/metrics"
    externalRef12 "github.com/dash0hq/dash0-cli/internal/api/types/otlpcommon"
)

// GetGroupedResourcesRequest defines model for GetGroupedResourcesRequest.
type GetGroupedResourcesRequest struct {
    // Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
    Dataset *externalRef5.Dataset        `json:"dataset,omitempty"`
    Filter  *externalRef8.FilterCriteria `json:"filter,omitempty"`

    // GroupBy Any resource attribute keys.
    GroupBy *externalRef9.GroupingCriteria `json:"groupBy,omitempty"`

    // IncludeResourceAttributeBreakdown If true, the response will contain additional information about Cloud, Orchestration and Language environment
    // for the grouped resources. Specific attributes for a single Resource are grouped together so that
    // the different permutations are correctly aggregated.
    IncludeResourceAttributeBreakdown *bool                             `json:"includeResourceAttributeBreakdown,omitempty"`
    Metrics                           *externalRef10.NamedMetricQueries `json:"metrics,omitempty"`

    // TimeRange A range of time between two time references.
    TimeRange externalRef6.TimeReferenceRange `json:"timeRange"`
}

// GetGroupedResourcesResponse defines model for GetGroupedResourcesResponse.
type GetGroupedResourcesResponse = []GroupedResources

type GroupedResources struct {
    Attributes []externalRef12.KeyValue `json:"attributes"`

    // Clouds Key-Value pairs with information on cloud environments in which these grouped resources are running. Only present when `includeResourceEnvironmentExtensions` is set to `true`!
    Clouds *[]externalRef3.ResourceAttributesBreakdown `json:"clouds,omitempty"`

    // DeploymentEnvironments Key-Value pairs with information on the deployment environment in which the resource is deployed. Only present when `includeResourceEnvironmentExtensions` is set to `true`!
    DeploymentEnvironments *[]externalRef3.ResourceAttributesBreakdown `json:"deploymentEnvironments,omitempty"`

    // FirstSeenUnixNano Key-Value pairs with information on cloud environments in which these grouped resources are running. Only present when `includeResourceEnvironmentExtensions` is set to `true`!
    FirstSeenUnixNano *string `json:"firstSeenUnixNano,omitempty"`
    Hash              string  `json:"hash"`

    // Languages Key-Value pairs with information on runtime environments in which these grouped resources are running. Only present when `includeResourceEnvironmentExtensions` is set to `true`!
    Languages *[]externalRef3.ResourceAttributesBreakdown `json:"languages,omitempty"`

    // LastSeenUnixNano Key-Value pairs with information on cloud environments in which these grouped resources are running. Only present when `includeResourceEnvironmentExtensions` is set to `true`!
    LastSeenUnixNano *string            `json:"lastSeenUnixNano,omitempty"`
    Metrics          *map[string]string `json:"metrics,omitempty"`
    OperationTypes   *[]string          `json:"operationTypes,omitempty"`

    // Orchestrations Key-Value pairs with information on platforms in which these grouped resources are running. Only present when `includeResourceEnvironmentExtensions` is set to `true`!
    Orchestrations *[]externalRef3.ResourceAttributesBreakdown `json:"orchestrations,omitempty"`
    ResourceCount  int64                                       `json:"resourceCount"`

    // ResourceCountIgnoringFilter What would the resource count be if no filter was supplied as part of the request. Used to show something like `x out of y resources` within the UI.
    ResourceCountIgnoringFilter *int64 `json:"resourceCountIgnoringFilter,omitempty"`

    // Services Key-Value pairs with information on services in which these grouped resources are running. Only present when `includeResourceEnvironmentExtensions` is set to `true`!
    Services *[]externalRef3.ResourceAttributesBreakdown `json:"services,omitempty"`
}
