// Package apiresources provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiresources

import (
	externalRef0 "github.com/dash0hq/dash0-cli/internal/api/types/common"
	externalRef1 "github.com/dash0hq/dash0-cli/internal/api/types/d0time"
	externalRef2 "github.com/dash0hq/dash0-cli/internal/api/types/filtering"
	externalRef3 "github.com/dash0hq/dash0-cli/internal/api/types/otlpcommon"
	externalRef4 "github.com/dash0hq/dash0-cli/internal/api/types/otlpresource"
	externalRef5 "github.com/dash0hq/dash0-cli/internal/api/types/pagination"
)

// DistinctResourceAttributeValueCounts defines model for DistinctResourceAttributeValueCounts.
type DistinctResourceAttributeValueCounts struct {
	Key   string `json:"key"`
	Total int    `json:"total"`
}

// GetResourceAttributeDistinctValueCountsRequest Request used to retrieve the list of unique attribute keys with their distinct value counts that exist on
// resources.
type GetResourceAttributeDistinctValueCountsRequest struct {
	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset *externalRef0.Dataset        `json:"dataset,omitempty"`
	Filter  *externalRef2.FilterCriteria `json:"filter,omitempty"`

	// OnlyGroupableKeys Should only groupable attribute keys be returned.
	OnlyGroupableKeys *bool `json:"onlyGroupableKeys,omitempty"`

	// TimeRange A range of time between two time references.
	TimeRange externalRef1.TimeReferenceRange `json:"timeRange"`
}

// GetResourceAttributeDistinctValueCountsResponse defines model for GetResourceAttributeDistinctValueCountsResponse.
type GetResourceAttributeDistinctValueCountsResponse = []DistinctResourceAttributeValueCounts

// GetResourceAttributeKeysRequest defines model for GetResourceAttributeKeysRequest.
type GetResourceAttributeKeysRequest struct {
	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset *externalRef0.Dataset        `json:"dataset,omitempty"`
	Filter  *externalRef2.FilterCriteria `json:"filter,omitempty"`

	// TimeRange A range of time between two time references.
	TimeRange externalRef1.TimeReferenceRange `json:"timeRange"`
}

// GetResourceAttributeKeysResponse defines model for GetResourceAttributeKeysResponse.
type GetResourceAttributeKeysResponse = []ValueAndCount

// GetResourceAttributeKeysValuesSearchRequest Request to discover keys and values matching a given search keyword. Depending on what the search keyword matches,
// returns potentially both matching keys with some top values, or matching values together with their attribute key.
type GetResourceAttributeKeysValuesSearchRequest struct {
	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset *externalRef0.Dataset        `json:"dataset,omitempty"`
	Filter  *externalRef2.FilterCriteria `json:"filter,omitempty"`

	// LimitByKey The maximum number of values per key to return. If not set, there is a default limit to the number of results returned.
	LimitByKey *int64 `json:"limitByKey,omitempty"`
	SearchTerm string `json:"searchTerm"`

	// TimeRange A range of time between two time references.
	TimeRange externalRef1.TimeReferenceRange `json:"timeRange"`
}

// GetResourceAttributeKeysValuesSearchResponse defines model for GetResourceAttributeKeysValuesSearchResponse.
type GetResourceAttributeKeysValuesSearchResponse map[string][]ValueAndCount

// GetResourceAttributeValuesRequest Request used to retrieve the list of unique attribute values per key that exist in resources for a given set of
// attribute keys.
type GetResourceAttributeValuesRequest struct {
	AttributeKeys []string `json:"attributeKeys"`

	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset *externalRef0.Dataset        `json:"dataset,omitempty"`
	Filter  *externalRef2.FilterCriteria `json:"filter,omitempty"`

	// LimitByKey The maximum number of values per key to return. If not set, there is a default limit to the number of results returned.
	LimitByKey *int64 `json:"limitByKey,omitempty"`

	// TimeRange A range of time between two time references.
	TimeRange externalRef1.TimeReferenceRange `json:"timeRange"`
}

// GetResourceAttributeValuesResponse defines model for GetResourceAttributeValuesResponse.
type GetResourceAttributeValuesResponse map[string][]ValueAndCount

// GetResourceRequest defines model for GetResourceRequest.
type GetResourceRequest struct {
	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset *externalRef0.Dataset `json:"dataset,omitempty"`

	// IncludeOTLPSchemaExtensions If true, the response will contain extension to the OTLP schema that are commonly used by API consumers.
	// These extensions are optional and may be omitted from the response for integration with other systems
	// that do not support them, e.g., those that use the OTLP schema directly.
	IncludeOTLPSchemaExtensions *bool  `json:"includeOTLPSchemaExtensions,omitempty"`
	ResourceId                  string `json:"resourceId"`

	// TimeRange A range of time between two time references.
	TimeRange *externalRef1.TimeReferenceRange `json:"timeRange,omitempty"`
}

// GetResourceResponse defines model for GetResourceResponse.
type GetResourceResponse = externalRef4.Resource

// GetResourcesRequest defines model for GetResourcesRequest.
type GetResourcesRequest struct {
	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset *externalRef0.Dataset        `json:"dataset,omitempty"`
	Filter  *externalRef2.FilterCriteria `json:"filter,omitempty"`

	// IncludeOTLPSchemaExtensions If true, the response will contain extension to the OTLP schema that are commonly used by API consumers.
	// These extensions are optional and may be omitted from the response for integration with other systems
	// that do not support them, e.g., those that use the OTLP schema directly.
	IncludeOTLPSchemaExtensions *bool `json:"includeOTLPSchemaExtensions,omitempty"`

	// Pagination Cursor pagination is a technique for paging through a result set using a cursor. It is
	// similar to offset pagination except that the cursor is an opaque value that encodes the
	// position within the result set. This allows for fetching the next page of results from
	// the current position without having to skip over a potentially large number of rows.
	//
	// It is also more resilient against late-arriving data which otherwise would cause issues
	// with offset pagination. For example, if a row is inserted between two pages of results
	// then the second page would contain a duplicate row and the third page would be missing.
	Pagination *externalRef5.CursorPagination `json:"pagination,omitempty"`

	// TimeRange A range of time between two time references.
	TimeRange externalRef1.TimeReferenceRange `json:"timeRange"`
}

// GetResourcesResponse Response for the `GetResources` API. The response contains the resources that match the request.
//
// This API deliberately reuses the full OTLP JSON format for resources, with the exception that it
// contains no further nested information such as Metrics or Logs. This is done to aid compatibility
// with existing OTLP consumers.
type GetResourcesResponse struct {
	Cursors       *externalRef5.NextCursors `json:"cursors,omitempty"`
	ExecutionTime *externalRef1.FixedTime   `json:"executionTime,omitempty"`

	// Resources `Resources` are **NOT** sorted. There is no guarantee that `Resources` are sorted. However,
	// it is guaranteed that all data is sorted across paged requests.
	Resources []externalRef4.Resource `json:"resources"`
	TimeRange *externalRef1.TimeRange `json:"timeRange,omitempty"`
}

// PostResourcesSearchRequest defines model for PostResourcesSearchRequest.
type PostResourcesSearchRequest struct {
	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset               *externalRef0.Dataset        `json:"dataset,omitempty"`
	Filter                *externalRef2.FilterCriteria `json:"filter,omitempty"`
	ResourceAttributeKeys []string                     `json:"resourceAttributeKeys"`

	// SearchTerm The search term to use to filter resources. The search term is matched against the values of any
	// of the given `resourceAttributeKeys` and `spanAttributeKeys`. The search term is case-insensitive
	// and supports partial matches. A match for a single attribute value is sufficient to include the
	// resource in the result.
	SearchTerm        string   `json:"searchTerm"`
	SpanAttributeKeys []string `json:"spanAttributeKeys"`

	// TimeRange A range of time between two time references.
	TimeRange externalRef1.TimeReferenceRange `json:"timeRange"`
}

// PostResourcesSearchResponse Response for the `postResourcesSearch` API. The response contains the resources that match the request.
type PostResourcesSearchResponse struct {
	ExecutionTime externalRef1.FixedTime `json:"executionTime"`

	// SearchResults `Resources` are **NOT** sorted. The resource attributes may be incomplete *and* they may mix
	// attributes from different signals.
	SearchResults []ResourcesSearchResult `json:"searchResults"`
	TimeRange     externalRef1.TimeRange  `json:"timeRange"`
}

// ResourceAttributesBreakdown defines model for ResourceAttributesBreakdown.
type ResourceAttributesBreakdown struct {
	Attributes []externalRef3.KeyValue `json:"attributes"`
}

// ResourcesSearchResult An attribute combination matching the given search term. The attribute combination
// contained herein depends in large parts on the attributes requested via `PostResourcesSearchRequest`.
type ResourcesSearchResult struct {
	Attributes []externalRef3.KeyValue `json:"attributes"`
}

// ValueAndCount defines model for ValueAndCount.
type ValueAndCount struct {
	Count int    `json:"count"`
	Value string `json:"value"`
}
