# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dash0 < Formula
  desc "CLI to interact with Dash0"
  homepage "https://github.com/dash0hq/dash0-cli"
  version "1.7.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.7.3/dash0_1.7.3_macos_amd64.tar.gz"
      sha256 "647756e88d2f49d326fc88a960979b14b64116c69d5847ef73fa120bca24aece"

      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.7.3/dash0_1.7.3_macos_arm64.tar.gz"
      sha256 "62754d4f223e660959c548c8aad65dad49ac76159e2161e02546bdf78bda08c9"

      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.7.3/dash0_1.7.3_linux_amd64.tar.gz"
      sha256 "cb96631e3edd79b87781ce7a0fef836fc9c8ab32585502877bc5db1042972a26"
      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.7.3/dash0_1.7.3_linux_arm.tar.gz"
      sha256 "152ca7a8e799251593d846c828629ea8beb143cb21a30848338aad312ee6f054"
      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.7.3/dash0_1.7.3_linux_arm64.tar.gz"
      sha256 "2d4c31d43643be880ca51baffa52c02b412b7d832b26cd836cdd7956367233bc"
      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
  end
end
