# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dash0 < Formula
  desc "CLI to interact with Dash0"
  homepage "https://github.com/dash0hq/dash0-cli"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.3.0/dash0_1.3.0_macos_amd64.tar.gz"
      sha256 "d51b2f0e1e111da3292f6afb8a6a1e527256297181f02545280b253619514a4e"

      def install
        bin.install "dash0"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.3.0/dash0_1.3.0_macos_arm64.tar.gz"
      sha256 "99741115f5d3d739cb22a64e77207daaed241ab7745cb241d9530bfd5a1a7993"

      def install
        bin.install "dash0"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.3.0/dash0_1.3.0_linux_amd64.tar.gz"
      sha256 "ff09efdaa480a723af600ee81f3d40bafa265f4d88b8fb6ec5ab1ed934fb2b36"
      def install
        bin.install "dash0"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.3.0/dash0_1.3.0_linux_arm.tar.gz"
      sha256 "87d2aaffe00c51fd8f068a37777fbd32d5ef98004606b2003b86ac55bd1782a2"
      def install
        bin.install "dash0"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.3.0/dash0_1.3.0_linux_arm64.tar.gz"
      sha256 "52c7f4c812f5bba50527cb136e48d8a0713f54169e9f5b35112062a9912b05aa"
      def install
        bin.install "dash0"
      end
    end
  end
end
