# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dash0 < Formula
  desc "CLI to interact with Dash0"
  homepage "https://github.com/dash0hq/dash0-cli"
  version "1.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.8.1/dash0_1.8.1_macos_amd64.tar.gz"
      sha256 "10016ba127c3025325bf2cde6d607cc5261e14978b5d9271d26662d69edb2d04"

      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.8.1/dash0_1.8.1_macos_arm64.tar.gz"
      sha256 "92c45c171f15df02b63e08d475904daba3647f650a06a1b39fda9d187fc9b7a6"

      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.8.1/dash0_1.8.1_linux_amd64.tar.gz"
      sha256 "a6bc8a72158b4e6f8d281df93bc29196e924a66d193e6c3e532b4cfcccb1d8c8"
      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.8.1/dash0_1.8.1_linux_arm.tar.gz"
      sha256 "60b981412fb9573f3adb71640af078534951b926ed311d178bb012475f4fdb49"
      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.8.1/dash0_1.8.1_linux_arm64.tar.gz"
      sha256 "19477d95b5d8b849a97ee25749f3f56fc4fb3d6bd8232e74b5a1ca66ff31f19d"
      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
  end
end
