// Package otlpcommon provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package otlpcommon

// AnyValue AnyValue is used to represent any type of attribute value. AnyValue may contain a primitive value such as a string or integer or it may contain an arbitrary nested object containing arrays, key-value lists and primitives.
type AnyValue struct {
	// ArrayValue ArrayValue is a list of AnyValue messages. We need ArrayValue as a message since oneof in AnyValue does not allow repeated fields.
	ArrayValue  *ArrayValue `json:"arrayValue,omitempty"`
	BoolValue   *bool       `json:"boolValue,omitempty"`
	BytesValue  *[]byte     `json:"bytesValue,omitempty"`
	DoubleValue *float64    `json:"doubleValue,omitempty"`
	IntValue    *string     `json:"intValue,omitempty"`

	// KvlistValue KeyValueList is a list of KeyValue messages. We need KeyValueList as a message since `oneof` in AnyValue does not allow repeated fields. Everywhere else where we need a list of KeyValue messages (e.g. in Span) we use `repeated KeyValue` directly to avoid unnecessary extra wrapping (which slows down the protocol). The 2 approaches are semantically equivalent.
	KvlistValue *KeyValueList `json:"kvlistValue,omitempty"`
	StringValue *string       `json:"stringValue,omitempty"`
}

// ArrayValue ArrayValue is a list of AnyValue messages. We need ArrayValue as a message since oneof in AnyValue does not allow repeated fields.
type ArrayValue struct {
	// Values Array of values. The array may be empty (contain 0 elements).
	Values []AnyValue `json:"values"`
}

// InstrumentationScope InstrumentationScope is a message representing the instrumentation scope information such as the fully qualified name and version.
type InstrumentationScope struct {
	// Attributes Additional attributes that describe the scope. [Optional]. Attribute keys MUST be unique (it is not allowed to have more than one attribute with the same key).
	Attributes             []KeyValue `json:"attributes"`
	DroppedAttributesCount *int64     `json:"droppedAttributesCount,omitempty"`

	// Name An empty instrumentation scope name means the name is unknown.
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

// KeyValue KeyValue is a key-value pair that is used to store Span attributes, Link attributes, etc.
type KeyValue struct {
	Key string `json:"key"`

	// Value AnyValue is used to represent any type of attribute value. AnyValue may contain a primitive value such as a string or integer or it may contain an arbitrary nested object containing arrays, key-value lists and primitives.
	Value AnyValue `json:"value"`
}

// KeyValueList KeyValueList is a list of KeyValue messages. We need KeyValueList as a message since `oneof` in AnyValue does not allow repeated fields. Everywhere else where we need a list of KeyValue messages (e.g. in Span) we use `repeated KeyValue` directly to avoid unnecessary extra wrapping (which slows down the protocol). The 2 approaches are semantically equivalent.
type KeyValueList struct {
	// Values A collection of key/value pairs of key-value pairs. The list may be empty (may contain 0 elements). The keys MUST be unique (it is not allowed to have more than one value with the same key).
	Values []KeyValue `json:"values"`
}

// Scope This type is used within some list responses. Consequently, it is a slight variation of the pure OTLP InstrumentationScope type.
type Scope struct {
	Name    string  `json:"name"`
	Version *string `json:"version,omitempty"`
}
