// Package grouping provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package grouping

// GroupingCriteria Any resource attribute keys.
type GroupingCriteria = []GroupingCriterion

// GroupingCriterion Any resource attribute key.
type GroupingCriterion = string
