// Package metrics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package metrics

import (
	externalRef0 "github.com/dash0hq/dash0-cli/internal/api/types/common"
	externalRef1 "github.com/dash0hq/dash0-cli/internal/api/types/d0time"
	externalRef2 "github.com/dash0hq/dash0-cli/internal/api/types/filtering"
	externalRef4 "github.com/dash0hq/dash0-cli/internal/api/types/ordering"
	externalRef7 "github.com/dash0hq/dash0-cli/internal/api/types/pagination"
)

// Defines values for MetricType.
const (
	MetricTypeExponentialHistogram MetricType = "exponential_histogram"
	MetricTypeGauge                MetricType = "gauge"
	MetricTypeHistogram            MetricType = "histogram"
	MetricTypeSum                  MetricType = "sum"
	MetricTypeSummary              MetricType = "summary"
	MetricTypeUnknown              MetricType = "unknown"
)

// Defines values for NamedMetricQuery.
// GetMetricCatalogRequest defines model for GetMetricCatalogRequest.
type GetMetricCatalogRequest struct {
	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset *externalRef0.Dataset        `json:"dataset,omitempty"`
	Filter  *externalRef2.FilterCriteria `json:"filter,omitempty"`

	// Ordering Any attribute keys to order by.
	Ordering *externalRef4.OrderingCriteria `json:"ordering,omitempty"`

	// Pagination Cursor pagination is a technique for paging through a result set using a cursor. It is
	// similar to offset pagination except that the cursor is an opaque value that encodes the
	// position within the result set. This allows for fetching the next page of results from
	// the current position without having to skip over a potentially large number of rows.
	//
	// It is also more resilient against late-arriving data which otherwise would cause issues
	// with offset pagination. For example, if a row is inserted between two pages of results
	// then the second page would contain a duplicate row and the third page would be missing.
	Pagination *externalRef7.CursorPagination `json:"pagination,omitempty"`

	// TimeRange A range of time between two time references.
	TimeRange externalRef1.TimeReferenceRange `json:"timeRange"`
}

// GetMetricCatalogResponse defines model for GetMetricCatalogResponse.
type GetMetricCatalogResponse struct {
	Catalog       []MetricCatalogItem      `json:"catalog"`
	Cursors       externalRef7.NextCursors `json:"cursors"`
	ExecutionTime externalRef1.FixedTime   `json:"executionTime"`
	TimeRange     externalRef1.TimeRange   `json:"timeRange"`
}

// MetricCatalogItem defines model for MetricCatalogItem.
type MetricCatalogItem struct {
	Name string `json:"name"`

	// Type The type of the metric. This controls how the metric is aggregated and visualized.
	Type   MetricType             `json:"type"`
	Unit   *string                `json:"unit,omitempty"`
	Usage  MetricUsageStatistics  `json:"usage"`
	Volume MetricVolumeStatistics `json:"volume"`
}

// MetricType The type of the metric. This controls how the metric is aggregated and visualized.
type MetricType string

// MetricUsageStatistics defines model for MetricUsageStatistics.
type MetricUsageStatistics struct {
	Checks     int64 `json:"checks"`
	Dashboards int64 `json:"dashboards"`
	Queries    int64 `json:"queries"`
}

// MetricVolumeStatistics defines model for MetricVolumeStatistics.
type MetricVolumeStatistics struct {
	Cardinality      int64   `json:"cardinality"`
	CardinalityScore float64 `json:"cardinalityScore"`
	DataPoints       int64   `json:"dataPoints"`
	Resources        int64   `json:"resources"`
}
