// Package metrics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package metrics

import (
	externalRef0 "github.com/dash0hq/dash0-cli/internal/api/types/common"
	externalRef1 "github.com/dash0hq/dash0-cli/internal/api/types/d0time"
	externalRef2 "github.com/dash0hq/dash0-cli/internal/api/types/filtering"
	externalRef4 "github.com/dash0hq/dash0-cli/internal/api/types/ordering"
	externalRef7 "github.com/dash0hq/dash0-cli/internal/api/types/pagination"
)

// Defines values for NamedMetricQuery.
const (
    NamedMetricQueryCheckEvaluationValue              NamedMetricQuery = "check_evaluation_value"
    NamedMetricQueryCheckStatus                       NamedMetricQuery = "check_status"
    NamedMetricQueryCheckThresholdCritical            NamedMetricQuery = "check_threshold_critical"
    NamedMetricQueryCheckThresholdDegraded            NamedMetricQuery = "check_threshold_degraded"
    NamedMetricQueryContainerCpuUsage                 NamedMetricQuery = "container_cpu_usage"
    NamedMetricQueryContainerCpuUtilization           NamedMetricQuery = "container_cpu_utilization"
    NamedMetricQueryDurationAvgSeconds                NamedMetricQuery = "duration_avg_seconds"
    NamedMetricQueryDurationAvgSecondsTrend           NamedMetricQuery = "duration_avg_seconds_trend"
    NamedMetricQueryDurationP50Seconds                NamedMetricQuery = "duration_p50_seconds"
    NamedMetricQueryDurationP50SecondsTrend           NamedMetricQuery = "duration_p50_seconds_trend"
    NamedMetricQueryDurationP75Seconds                NamedMetricQuery = "duration_p75_seconds"
    NamedMetricQueryDurationP75SecondsTrend           NamedMetricQuery = "duration_p75_seconds_trend"
    NamedMetricQueryDurationP90Seconds                NamedMetricQuery = "duration_p90_seconds"
    NamedMetricQueryDurationP90SecondsTrend           NamedMetricQuery = "duration_p90_seconds_trend"
    NamedMetricQueryDurationP95Seconds                NamedMetricQuery = "duration_p95_seconds"
    NamedMetricQueryDurationP95SecondsTrend           NamedMetricQuery = "duration_p95_seconds_trend"
    NamedMetricQueryDurationP99Seconds                NamedMetricQuery = "duration_p99_seconds"
    NamedMetricQueryDurationP99SecondsTrend           NamedMetricQuery = "duration_p99_seconds_trend"
    NamedMetricQueryDurationPmaxSeconds               NamedMetricQuery = "duration_pmax_seconds"
    NamedMetricQueryDurationPmaxSecondsTrend          NamedMetricQuery = "duration_pmax_seconds_trend"
    NamedMetricQueryErrorsPercentage                  NamedMetricQuery = "errors_percentage"
    NamedMetricQueryErrorsPercentageTrend             NamedMetricQuery = "errors_percentage_trend"
    NamedMetricQueryErrorsRate                        NamedMetricQuery = "errors_rate"
    NamedMetricQueryErrorsRateTrend                   NamedMetricQuery = "errors_rate_trend"
    NamedMetricQueryErrorsTotal                       NamedMetricQuery = "errors_total"
    NamedMetricQueryErrorsTotalTrend                  NamedMetricQuery = "errors_total_trend"
    NamedMetricQueryFailedChecksCriticalTotal         NamedMetricQuery = "failed_checks_critical_total"
    NamedMetricQueryFailedChecksDegradedTotal         NamedMetricQuery = "failed_checks_degraded_total"
    NamedMetricQueryFailedChecksTotal                 NamedMetricQuery = "failed_checks_total"
    NamedMetricQueryIssueStatus                       NamedMetricQuery = "issue_status"
    NamedMetricQueryIssuesCriticalTotal               NamedMetricQuery = "issues_critical_total"
    NamedMetricQueryIssuesDegradedTotal               NamedMetricQuery = "issues_degraded_total"
    NamedMetricQueryIssuesTotal                       NamedMetricQuery = "issues_total"
    NamedMetricQueryK8sContainerNotReady              NamedMetricQuery = "k8s_container_not_ready"
    NamedMetricQueryK8sContainerReady                 NamedMetricQuery = "k8s_container_ready"
    NamedMetricQueryK8sCronjobActiveJobs              NamedMetricQuery = "k8s_cronjob_active_jobs"
    NamedMetricQueryK8sCronjobActivePods              NamedMetricQuery = "k8s_cronjob_active_pods"
    NamedMetricQueryK8sCronjobDesiredSuccessfulPods   NamedMetricQuery = "k8s_cronjob_desired_successful_pods"
    NamedMetricQueryK8sCronjobFailedPods              NamedMetricQuery = "k8s_cronjob_failed_pods"
    NamedMetricQueryK8sCronjobSuccessfulPods          NamedMetricQuery = "k8s_cronjob_successful_pods"
    NamedMetricQueryK8sDaemonsetCount                 NamedMetricQuery = "k8s_daemonset_count"
    NamedMetricQueryK8sDaemonsetCurrentScheduledNodes NamedMetricQuery = "k8s_daemonset_current_scheduled_nodes"
    NamedMetricQueryK8sDaemonsetDesiredScheduledNodes NamedMetricQuery = "k8s_daemonset_desired_scheduled_nodes"
    NamedMetricQueryK8sDaemonsetMisscheduledNodes     NamedMetricQuery = "k8s_daemonset_misscheduled_nodes"
    NamedMetricQueryK8sDaemonsetReadyNodes            NamedMetricQuery = "k8s_daemonset_ready_nodes"
    NamedMetricQueryK8sDeploymentAvailable            NamedMetricQuery = "k8s_deployment_available"
    NamedMetricQueryK8sDeploymentDesired              NamedMetricQuery = "k8s_deployment_desired"
    NamedMetricQueryK8sJobActivePods                  NamedMetricQuery = "k8s_job_active_pods"
    NamedMetricQueryK8sJobCount                       NamedMetricQuery = "k8s_job_count"
    NamedMetricQueryK8sJobDesiredSuccessfulPods       NamedMetricQuery = "k8s_job_desired_successful_pods"
    NamedMetricQueryK8sJobFailedPods                  NamedMetricQuery = "k8s_job_failed_pods"
    NamedMetricQueryK8sJobMaxParallelPods             NamedMetricQuery = "k8s_job_max_parallel_pods"
    NamedMetricQueryK8sJobSuccessfulPods              NamedMetricQuery = "k8s_job_successful_pods"
    NamedMetricQueryK8sNodeCpuUsage                   NamedMetricQuery = "k8s_node_cpu_usage"
    NamedMetricQueryK8sNodeCpuUtilization             NamedMetricQuery = "k8s_node_cpu_utilization"
    NamedMetricQueryK8sNodeFilesystemAvailable        NamedMetricQuery = "k8s_node_filesystem_available"
    NamedMetricQueryK8sNodeFilesystemCapacity         NamedMetricQuery = "k8s_node_filesystem_capacity"
    NamedMetricQueryK8sNodeFilesystemUsage            NamedMetricQuery = "k8s_node_filesystem_usage"
    NamedMetricQueryK8sNodeMemoryAvailable            NamedMetricQuery = "k8s_node_memory_available"
    NamedMetricQueryK8sNodeMemoryUsage                NamedMetricQuery = "k8s_node_memory_usage"
    NamedMetricQueryK8sNodeStatus                     NamedMetricQuery = "k8s_node_status"
    NamedMetricQueryK8sPodCount                       NamedMetricQuery = "k8s_pod_count"
    NamedMetricQueryK8sPodCpuLimitUtilization         NamedMetricQuery = "k8s_pod_cpu_limit_utilization"
    NamedMetricQueryK8sPodCpuRequestUtilization       NamedMetricQuery = "k8s_pod_cpu_request_utilization"
    NamedMetricQueryK8sPodCpuUsage                    NamedMetricQuery = "k8s_pod_cpu_usage"
    NamedMetricQueryK8sPodCpuUtilization              NamedMetricQuery = "k8s_pod_cpu_utilization"
    NamedMetricQueryK8sPodMemoryLimitUtilization      NamedMetricQuery = "k8s_pod_memory_limit_utilization"
    NamedMetricQueryK8sPodMemoryRequestUtilization    NamedMetricQuery = "k8s_pod_memory_request_utilization"
    NamedMetricQueryK8sPodMemoryUsage                 NamedMetricQuery = "k8s_pod_memory_usage"
    NamedMetricQueryK8sPodStatus                      NamedMetricQuery = "k8s_pod_status"
    NamedMetricQueryK8sPodStatusFailedCount           NamedMetricQuery = "k8s_pod_status_failed_count"
    NamedMetricQueryK8sPodStatusPendingCount          NamedMetricQuery = "k8s_pod_status_pending_count"
    NamedMetricQueryK8sPodStatusRunningCount          NamedMetricQuery = "k8s_pod_status_running_count"
    NamedMetricQueryK8sPodStatusSucceededCount        NamedMetricQuery = "k8s_pod_status_succeeded_count"
    NamedMetricQueryK8sReplicasetAvailable            NamedMetricQuery = "k8s_replicaset_available"
    NamedMetricQueryK8sReplicasetAvailableCount       NamedMetricQuery = "k8s_replicaset_available_count"
    NamedMetricQueryK8sReplicasetCount                NamedMetricQuery = "k8s_replicaset_count"
    NamedMetricQueryK8sReplicasetDesired              NamedMetricQuery = "k8s_replicaset_desired"
    NamedMetricQueryK8sStatefulsetCount               NamedMetricQuery = "k8s_statefulset_count"
    NamedMetricQueryK8sStatefulsetDesiredPods         NamedMetricQuery = "k8s_statefulset_desired_pods"
    NamedMetricQueryK8sStatefulsetReadyPods           NamedMetricQuery = "k8s_statefulset_ready_pods"
    NamedMetricQueryK8sStatefulsetUpdatedPods         NamedMetricQuery = "k8s_statefulset_updated_pods"
    NamedMetricQueryLogsDebugOrTraceTotal             NamedMetricQuery = "logs_debug_or_trace_total"
    NamedMetricQueryLogsErrorOrFatalTotal             NamedMetricQuery = "logs_error_or_fatal_total"
    NamedMetricQueryLogsInfoTotal                     NamedMetricQuery = "logs_info_total"
    NamedMetricQueryLogsTotal                         NamedMetricQuery = "logs_total"
    NamedMetricQueryLogsUnknownTotal                  NamedMetricQuery = "logs_unknown_total"
    NamedMetricQueryLogsWarnTotal                     NamedMetricQuery = "logs_warn_total"
    NamedMetricQueryMetricDatapointsTotal             NamedMetricQuery = "metric_datapoints_total"
    NamedMetricQueryRequests1xxTotal                  NamedMetricQuery = "requests_1xx_total"
    NamedMetricQueryRequests2xxTotal                  NamedMetricQuery = "requests_2xx_total"
    NamedMetricQueryRequests3xxTotal                  NamedMetricQuery = "requests_3xx_total"
    NamedMetricQueryRequests4xxTotal                  NamedMetricQuery = "requests_4xx_total"
    NamedMetricQueryRequests5xxTotal                  NamedMetricQuery = "requests_5xx_total"
    NamedMetricQueryRequestsRate                      NamedMetricQuery = "requests_rate"
    NamedMetricQueryRequestsRateTrend                 NamedMetricQuery = "requests_rate_trend"
    NamedMetricQueryRequestsTotal                     NamedMetricQuery = "requests_total"
    NamedMetricQueryRequestsTotalTrend                NamedMetricQuery = "requests_total_trend"
    NamedMetricQueryResourceGroups                    NamedMetricQuery = "resource_groups"
    NamedMetricQueryResources                         NamedMetricQuery = "resources"
    NamedMetricQuerySpansErrorTotal                   NamedMetricQuery = "spans_error_total"
    NamedMetricQuerySpansOkOrUnsetTotal               NamedMetricQuery = "spans_ok_or_unset_total"
    NamedMetricQuerySpansTotal                        NamedMetricQuery = "spans_total"
)

// Defines values for MetricType.
const (
	MetricTypeExponentialHistogram MetricType = "exponential_histogram"
	MetricTypeGauge                MetricType = "gauge"
	MetricTypeHistogram            MetricType = "histogram"
	MetricTypeSum                  MetricType = "sum"
	MetricTypeSummary              MetricType = "summary"
	MetricTypeUnknown              MetricType = "unknown"
)

// Defines values for NamedMetricQuery.
// GetMetricCatalogRequest defines model for GetMetricCatalogRequest.
type GetMetricCatalogRequest struct {
	// Dataset Optional dataset to query across. Defaults to whatever is configured to be the default dataset for the organization.
	Dataset *externalRef0.Dataset        `json:"dataset,omitempty"`
	Filter  *externalRef2.FilterCriteria `json:"filter,omitempty"`

	// Ordering Any attribute keys to order by.
	Ordering *externalRef4.OrderingCriteria `json:"ordering,omitempty"`

	// Pagination Cursor pagination is a technique for paging through a result set using a cursor. It is
	// similar to offset pagination except that the cursor is an opaque value that encodes the
	// position within the result set. This allows for fetching the next page of results from
	// the current position without having to skip over a potentially large number of rows.
	//
	// It is also more resilient against late-arriving data which otherwise would cause issues
	// with offset pagination. For example, if a row is inserted between two pages of results
	// then the second page would contain a duplicate row and the third page would be missing.
	Pagination *externalRef7.CursorPagination `json:"pagination,omitempty"`

	// TimeRange A range of time between two time references.
	TimeRange externalRef1.TimeReferenceRange `json:"timeRange"`
}

// GetMetricCatalogResponse defines model for GetMetricCatalogResponse.
type GetMetricCatalogResponse struct {
	Catalog       []MetricCatalogItem      `json:"catalog"`
	Cursors       externalRef7.NextCursors `json:"cursors"`
	ExecutionTime externalRef1.FixedTime   `json:"executionTime"`
	TimeRange     externalRef1.TimeRange   `json:"timeRange"`
}

// MetricCatalogItem defines model for MetricCatalogItem.
type MetricCatalogItem struct {
	Name string `json:"name"`

	// Type The type of the metric. This controls how the metric is aggregated and visualized.
	Type   MetricType             `json:"type"`
	Unit   *string                `json:"unit,omitempty"`
	Usage  MetricUsageStatistics  `json:"usage"`
	Volume MetricVolumeStatistics `json:"volume"`
}

// MetricType The type of the metric. This controls how the metric is aggregated and visualized.
type MetricType string

// MetricUsageStatistics defines model for MetricUsageStatistics.
type MetricUsageStatistics struct {
	Checks     int64 `json:"checks"`
	Dashboards int64 `json:"dashboards"`
	Queries    int64 `json:"queries"`
}

// MetricVolumeStatistics defines model for MetricVolumeStatistics.
type MetricVolumeStatistics struct {
	Cardinality      int64   `json:"cardinality"`
	CardinalityScore float64 `json:"cardinalityScore"`
	DataPoints       int64   `json:"dataPoints"`
	Resources        int64   `json:"resources"`
}

// NamedMetricQueries defines model for NamedMetricQueries.
type NamedMetricQueries = []NamedMetricQuery

// NamedMetricQuery A named metric query models a semantic name for a specific metric. Named metric queries are often easier to use than PromQL queries.
type NamedMetricQuery string
