// Package ordering provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ordering

// Defines values for OrderingDirection.
const (
	OrderingDirectionAscending  OrderingDirection = "ascending"
	OrderingDirectionDescending OrderingDirection = "descending"
)

// OrderingCriteria Any attribute keys to order by.
type OrderingCriteria = []OrderingCriterion

// OrderingCriterion Any combination of a key to order by and a direction.
type OrderingCriterion struct {
	Direction OrderingDirection `json:"direction"`

	// Key Any attribute key to order by.
	Key OrderingKey `json:"key"`
}

// OrderingDirection defines model for OrderingDirection.
type OrderingDirection string

// OrderingKey Any attribute key to order by.
type OrderingKey = string
